/**
 * Seed — popula a tabela questions com todas as questões
 * Execute: npm run db:seed
 */
import { db, questions } from "./index";

const QUESTOES = [
  // ── LÍNGUA PORTUGUESA ──
  { id:"p01", area:"port", sub:"Interpretação de Texto", banca:"CESGRANRIO", ano:2018, dif:"media", tipo:"multipla", enfase:"adm_controle",
    enunciado:"Leia o trecho: 'A exploração de petróleo em águas profundas exige tecnologia de ponta e investimentos vultosos, mas os retornos financeiros justificam os riscos envolvidos.' A expressão 'tecnologia de ponta' equivale a:",
    opcoes:["Tecnologia obsoleta","Tecnologia avançada e moderna","Tecnologia barata e acessível","Tecnologia importada","Tecnologia experimental"],
    correta:1, explicacao:"'Tecnologia de ponta' significa tecnologia mais avançada e sofisticada. Interpretação semântica é recorrente nas provas Cesgranrio/Petrobras." },
  { id:"p02", area:"port", sub:"Concordância Verbal", banca:"CESGRANRIO", ano:2018, dif:"media", tipo:"multipla", enfase:"adm_controle",
    enunciado:"Assinale a alternativa com concordância verbal CORRETA conforme a norma culta:",
    opcoes:["Faz anos que os técnicos trabalham nessa plataforma.","Fazem anos que os técnicos trabalha nessa plataforma.","Faz anos que o técnico trabalharam nessa plataforma.","Fazem anos que o técnico trabalhou nessa plataforma.","Faz anos que os técnicos trabalhou nessa plataforma."],
    correta:0, explicacao:"'Fazer' indicando tempo é impessoal — sempre singular. 'Trabalham' concorda com 'os técnicos'." },
  { id:"p03", area:"port", sub:"Crase", banca:"CESGRANRIO", ano:2014, dif:"facil", tipo:"multipla", enfase:"adm_controle",
    enunciado:"Em qual alternativa o uso da crase está CORRETO?",
    opcoes:["O engenheiro foi à reunião de segurança.","O técnico voltou à trabalhar na refinaria.","Entregue o relatório à ele antes do prazo.","Chegaremos à tempo para a vistoria.","Eles se referiram à documentos técnicos."],
    correta:0, explicacao:"Crase: preposição 'a' + artigo 'a'. Em 'foi à reunião' há fusão correta pois 'reunião' é feminino e o verbo exige preposição." },
  { id:"p04", area:"port", sub:"Pontuação", banca:"CESGRANRIO", ano:2018, dif:"media", tipo:"multipla", enfase:"adm_controle",
    enunciado:"Analise: 'Os engenheiros, que trabalhavam na plataforma P-36, foram evacuados.' Essa vírgula indica:",
    opcoes:["Oração adjetiva restritiva","Oração adjetiva explicativa","Inversão da ordem direta","Aposto explicativo","Adjunto adverbial deslocado"],
    correta:1, explicacao:"Adjetiva EXPLICATIVA — acrescenta informação extra sobre todos os engenheiros. Restritivas não levam vírgula." },
  { id:"p05", area:"port", sub:"Semântica", banca:"CEBRASPE", ano:2024, dif:"media", tipo:"certo_errado", enfase:"adm_controle",
    enunciado:"A palavra 'vultoso' (como em 'investimentos vultosos') pode ser substituída por 'ínfimos' sem alterar o sentido original.",
    opcoes:["CERTO","ERRADO"], correta:1, explicacao:"ERRADO. 'Vultoso' = grande/volumoso. 'Ínfimo' é antônimo. A substituição inverteria o sentido." },
  { id:"p06", area:"port", sub:"Regência Verbal", banca:"CESGRANRIO", ano:2017, dif:"dificil", tipo:"multipla", enfase:"adm_controle",
    enunciado:"Assinale a alternativa em que a regência verbal está em conformidade com a norma culta:",
    opcoes:["Os operadores assistiram o acidente da sala de controle.","A empresa visa ao cumprimento das metas de segurança.","O gerente prefere a proposta nova do que a antiga.","Todos os técnicos chegaram em São Paulo ontem.","A Petrobras informou os funcionários sobre as mudanças."],
    correta:1, explicacao:"'Visar' (objetivar) é VTI e pede 'a': 'visa AO cumprimento'." },
  { id:"p07", area:"port", sub:"Interpretação", banca:"CEBRASPE", ano:2024, dif:"media", tipo:"certo_errado", enfase:"adm_controle",
    enunciado:"Texto: 'A Petrobras opera em mais de 15 países. Apesar de ser majoritariamente estatal, suas ações são negociadas nas bolsas do Brasil e dos EUA.' — O texto apresenta a Petrobras como empresa exclusivamente privada.",
    opcoes:["CERTO","ERRADO"], correta:1, explicacao:"ERRADO. O texto diz 'majoritariamente estatal'. Ter ações em bolsa não a torna exclusivamente privada." },
  { id:"p08", area:"port", sub:"Ortografia", banca:"CESGRANRIO", ano:2018, dif:"facil", tipo:"multipla", enfase:"adm_controle",
    enunciado:"Todas as palavras estão grafadas CORRETAMENTE em:",
    opcoes:["excessão, privilégio, beneficiente","exceção, privilégio, beneficente","excessão, prevégio, beneficente","exceção, previlério, beneficiente","exceção, priviléjo, beneficente"],
    correta:1, explicacao:"'Exceção', 'privilégio', 'beneficente' (sem 'i' antes do 'ente')." },
  { id:"p09", area:"port", sub:"Pressupostos", banca:"CESGRANRIO", ano:2018, dif:"dificil", tipo:"multipla", enfase:"adm_controle",
    enunciado:"Em 'O técnico parou de usar EPI durante a vistoria', há um pressuposto de que:",
    opcoes:["O técnico nunca usou EPI","O técnico usava EPI antes","A vistoria foi cancelada","O EPI é desnecessário","O técnico será punido"],
    correta:1, explicacao:"'Parar de' pressupõe que a ação era realizada antes." },
  { id:"p10", area:"port", sub:"Pronomes Relativos", banca:"CESGRANRIO", ano:2018, dif:"media", tipo:"multipla", enfase:"adm_controle",
    enunciado:"Assinale a alternativa com pronome relativo empregado CORRETAMENTE:",
    opcoes:["O equipamento que eu me refiro está quebrado.","O técnico a quem supervisiona a obra está ausente.","A plataforma de que me refiro fica no pré-sal.","O engenheiro com quem trabalhei é competente.","O projeto que depositamos a esperança foi aprovado."],
    correta:3, explicacao:"'Com quem' correto — preposição 'com' + pronome 'quem' para referir-se a pessoa." },
  { id:"p11", area:"port", sub:"Conjunções", banca:"CESGRANRIO", ano:2018, dif:"media", tipo:"multipla", enfase:"adm_controle",
    enunciado:"Conjunção de CAUSA: 'A produção foi interrompida ___ houve um vazamento.'",
    opcoes:["mas","portanto","porque","porém","contudo"],
    correta:2, explicacao:"'Porque' é conjunção causal. 'Mas/porém/contudo' são adversativas. 'Portanto' é conclusiva." },
  // ── MATEMÁTICA ──
  { id:"m01", area:"mat", sub:"Porcentagem", banca:"CESGRANRIO", ano:2018, dif:"facil", tipo:"multipla", enfase:"adm_controle",
    enunciado:"Uma refinaria processou 80.000 barris em janeiro. Em fevereiro houve aumento de 15%. Quantos barris em fevereiro?",
    opcoes:["88.000","90.000","92.000","94.000","96.000"],
    correta:2, explicacao:"80.000 × 1,15 = 92.000. Porcentagem é o tema mais cobrado em matemática nas provas Cesgranrio." },
  { id:"m02", area:"mat", sub:"Juros Simples", banca:"CESGRANRIO", ano:2018, dif:"media", tipo:"multipla", enfase:"adm_controle",
    enunciado:"R$ 5.000 a juros simples de 2% ao mês. Montante após 6 meses:",
    opcoes:["R$ 5.500,00","R$ 5.600,00","R$ 5.300,00","R$ 5.400,00","R$ 6.000,00"],
    correta:1, explicacao:"J = 5000 × 0,02 × 6 = 600. Montante = 5.600,00." },
  { id:"m03", area:"mat", sub:"Razão e Proporção", banca:"CESGRANRIO", ano:2014, dif:"media", tipo:"multipla", enfase:"adm_controle",
    enunciado:"Proporção técnicos/engenheiros = 5:2. Há 35 técnicos. Quantos engenheiros?",
    opcoes:["10","12","14","16","18"], correta:2, explicacao:"5/2 = 35/x → x = 14 engenheiros." },
  { id:"m04", area:"mat", sub:"Progressão Aritmética", banca:"CESGRANRIO", ano:2018, dif:"media", tipo:"multipla", enfase:"adm_controle",
    enunciado:"PA de produção: 1.000; 1.200; 1.400; ... Produção no 10º dia?",
    opcoes:["2.600","2.700","2.800","2.900","3.000"], correta:2, explicacao:"a₁₀ = 1000 + 9×200 = 2.800." },
  { id:"m05", area:"mat", sub:"Análise Combinatória", banca:"CESGRANRIO", ano:2014, dif:"dificil", tipo:"multipla", enfase:"adm_controle",
    enunciado:"Com {1,2,3,4,5}, quantos números de 3 algarismos distintos?",
    opcoes:["30","45","60","90","120"], correta:2, explicacao:"A(5,3) = 5×4×3 = 60." },
  { id:"m06", area:"mat", sub:"Lógica Proposicional", banca:"CESGRANRIO", ano:2017, dif:"dificil", tipo:"multipla", enfase:"adm_controle",
    enunciado:"Negação de 'Se P então Q' é:",
    opcoes:["¬P e ¬Q","P e ¬Q","Se ¬P então ¬Q","¬P ou Q","Se Q então P"],
    correta:1, explicacao:"Negação de P→Q é P∧¬Q." },
  { id:"m07", area:"mat", sub:"Geometria Plana", banca:"CESGRANRIO", ano:2018, dif:"media", tipo:"multipla", enfase:"adm_controle",
    enunciado:"Tanque circular raio 7m. Área (π≈3,14):",
    opcoes:["130,05 m²","146,58 m²","153,86 m²","160,12 m²","175,20 m²"],
    correta:2, explicacao:"π×7² = 3,14×49 = 153,86 m²." },
  { id:"m08", area:"mat", sub:"Diagrama de Venn", banca:"CESGRANRIO", ano:2017, dif:"media", tipo:"multipla", enfase:"adm_controle",
    enunciado:"50 técnicos: 30 soldagem, 20 elétrica, 8 ambas. Apenas uma das duas?",
    opcoes:["22","28","34","40","42"], correta:2, explicacao:"(30-8)+(20-8) = 22+12 = 34." },
  { id:"m09", area:"mat", sub:"Juros Compostos", banca:"CESGRANRIO", ano:2018, dif:"dificil", tipo:"multipla", enfase:"adm_controle",
    enunciado:"R$ 10.000 a juros compostos 10%/período. Montante após 3 períodos [(1,1)³=1,331]:",
    opcoes:["R$ 13.000,00","R$ 13.100,00","R$ 13.310,00","R$ 13.200,00","R$ 13.410,00"],
    correta:2, explicacao:"M = 10.000×1,331 = R$ 13.310,00." },
  { id:"m10", area:"mat", sub:"Estatística", banca:"CESGRANRIO", ano:2014, dif:"facil", tipo:"multipla", enfase:"adm_controle",
    enunciado:"Tempos de resposta: 3,5,5,7,10. Média:",
    opcoes:["5","5,5","6","6,5","7"], correta:2, explicacao:"(3+5+5+7+10)/5 = 6." },
  { id:"m11", area:"mat", sub:"Probabilidade", banca:"CESGRANRIO", ano:2018, dif:"media", tipo:"multipla", enfase:"adm_controle",
    enunciado:"100 válvulas, 5 defeituosas. Probabilidade de sortear uma defeituosa:",
    opcoes:["1/10","1/15","1/20","1/25","1/50"], correta:2, explicacao:"5/100 = 1/20." },
  // ── INFORMÁTICA ──
  { id:"i01", area:"info", sub:"Segurança — Phishing", banca:"CESGRANRIO", ano:2018, dif:"media", tipo:"multipla", enfase:"adm_controle",
    enunciado:"E-mail falso pedindo dados via link. Esse ataque é:",
    opcoes:["Ransomware","Phishing","Trojan","Keylogger","Spyware"],
    correta:1, explicacao:"Phishing = golpe de personificação para obter dados." },
  { id:"i02", area:"info", sub:"Excel — MÉDIA", banca:"CESGRANRIO", ano:2018, dif:"facil", tipo:"multipla", enfase:"adm_controle",
    enunciado:"No Excel, média de A1:A10:",
    opcoes:["=SOMA(A1:A10)/10","=MÉDIA(A1;A10)","=MÉDIA(A1:A10)","=CALCMEDIA(A1,A10)","=AVG(A1:A10)"],
    correta:2, explicacao:"=MÉDIA(A1:A10) usa ':' para intervalo contínuo." },
  { id:"i03", area:"info", sub:"Protocolos — SMTP", banca:"CESGRANRIO", ano:2018, dif:"media", tipo:"multipla", enfase:"adm_controle",
    enunciado:"Protocolo de envio de e-mails entre servidores:",
    opcoes:["HTTP","FTP","SMTP","POP3","IMAP"],
    correta:2, explicacao:"SMTP = envio. POP3/IMAP = recebimento. HTTP = web. FTP = arquivos." },
  { id:"i04", area:"info", sub:"Firewall", banca:"CESGRANRIO", ano:2018, dif:"media", tipo:"multipla", enfase:"adm_controle",
    enunciado:"Principal função do firewall:",
    opcoes:["Acelerar conexão","Filtrar e controlar tráfego, bloqueando acessos não autorizados","Armazenar backups","Gerenciar senhas","Converter IPs"],
    correta:1, explicacao:"Firewall inspeciona tráfego e aplica regras de bloqueio/permissão." },
  { id:"i05", area:"info", sub:"Windows — Atalhos", banca:"CESGRANRIO", ano:2014, dif:"facil", tipo:"multipla", enfase:"adm_controle",
    enunciado:"Atalho para COPIAR no Windows:",
    opcoes:["Ctrl+X","Ctrl+V","Ctrl+Z","Ctrl+C","Ctrl+A"],
    correta:3, explicacao:"Ctrl+C = Copiar. Ctrl+X = Recortar. Ctrl+V = Colar." },
  { id:"i06", area:"info", sub:"Hardware — CPU", banca:"CESGRANRIO", ano:2018, dif:"facil", tipo:"multipla", enfase:"adm_controle",
    enunciado:"Componente responsável pelo processamento central:",
    opcoes:["HD","RAM","CPU","GPU","Fonte"],
    correta:2, explicacao:"CPU = processador central. HD armazena, RAM é memória temporária." },
  { id:"i07", area:"info", sub:"SQL — SELECT", banca:"CESGRANRIO", ano:2018, dif:"media", tipo:"multipla", enfase:"adm_controle",
    enunciado:"Comando SQL para RECUPERAR dados:",
    opcoes:["INSERT","UPDATE","DELETE","SELECT","CREATE"],
    correta:3, explicacao:"SELECT recupera. INSERT insere, UPDATE atualiza, DELETE remove." },
  { id:"i08", area:"info", sub:"Python — Dicionário", banca:"CESGRANRIO", ano:2018, dif:"dificil", tipo:"multipla", enfase:"adm_controle",
    enunciado:"Estrutura Python que armazena pares chave-valor:",
    opcoes:["list","tuple","set","dict","queue"],
    correta:3, explicacao:"dict = dicionário, par chave:valor, acesso O(1)." },
  { id:"i09", area:"info", sub:"Cloud — IaaS", banca:"CEBRASPE", ano:2024, dif:"media", tipo:"multipla", enfase:"adm_controle",
    enunciado:"Nuvem: provedor dá infraestrutura, cliente gerencia SO e apps:",
    opcoes:["SaaS","PaaS","IaaS","FaaS","DaaS"],
    correta:2, explicacao:"IaaS = Infrastructure as a Service." },
  // ── ADMINISTRAÇÃO ──
  { id:"a01", area:"adm", sub:"Funções Administrativas — PODC", banca:"CESGRANRIO", ano:2018, dif:"facil", tipo:"multipla", enfase:"adm_controle",
    enunciado:"Funções clássicas de Fayol:",
    opcoes:["PODA","PDCA","PODC","SWOT","BSC"],
    correta:2, explicacao:"PODC = Planejamento, Organização, Direção e Controle." },
  { id:"a02", area:"adm", sub:"Gestão por Competências — CHA", banca:"CESGRANRIO", ano:2018, dif:"facil", tipo:"multipla", enfase:"adm_controle",
    enunciado:"CHA na gestão por competências:",
    opcoes:["Cargo, Hierarquia e Avaliação","Conhecimentos, Habilidades e Atitudes","Controle, Hierarquia e Ação","Capacidade, Habilidade e Atividade","Competência, Hierarquia e Aprendizado"],
    correta:1, explicacao:"CHA: Conhecimentos (saber), Habilidades (saber fazer), Atitudes (querer fazer)." },
  { id:"a03", area:"adm", sub:"Gestão de Estoques", banca:"CESGRANRIO", ano:2018, dif:"media", tipo:"multipla", enfase:"adm_controle",
    enunciado:"Nível de estoque que dispara novo pedido:",
    opcoes:["Estoque de segurança","Ponto de pedido","Estoque máximo","Lote econômico","FIFO"],
    correta:1, explicacao:"Ponto de Pedido = nível que sinaliza emissão de novo pedido." },
  { id:"a04", area:"adm", sub:"SWOT", banca:"CESGRANRIO", ano:2018, dif:"facil", tipo:"multipla", enfase:"adm_controle",
    enunciado:"Na análise SWOT, 'T' significa:",
    opcoes:["Tendências","Tecnologia","Ameaças (Threats)","Talentos","Tarefas"],
    correta:2, explicacao:"SWOT: Strengths, Weaknesses, Opportunities, Threats." },
  { id:"a05", area:"adm", sub:"Lei 13.303/2016", banca:"CESGRANRIO", ano:2018, dif:"dificil", tipo:"multipla", enfase:"adm_controle",
    enunciado:"Dispensa de licitação em obras pela Lei 13.303/2016 até:",
    opcoes:["R$ 8.000,00","R$ 50.000,00","R$ 100.000,00","R$ 10.000,00","R$ 500.000,00"],
    correta:2, explicacao:"Art. 29: obras/engenharia até R$ 100.000,00; outros até R$ 50.000,00." },
  { id:"a06", area:"adm", sub:"Avaliação 360°", banca:"CESGRANRIO", ano:2014, dif:"media", tipo:"multipla", enfase:"adm_controle",
    enunciado:"Avaliação de desempenho 360 graus se caracteriza por:",
    opcoes:["Apenas resultados financeiros","Só pelo gestor","Feedback de chefes, pares, subordinados e autoavaliação","Só para liderança","Substituir o gestor"],
    correta:2, explicacao:"360° = múltiplos avaliadores: superior, pares, subordinados e autoavaliação." },
  { id:"a07", area:"adm", sub:"PMBOK — Fases", banca:"CEBRASPE", ano:2024, dif:"media", tipo:"multipla", enfase:"adm_controle",
    enunciado:"Fases do ciclo de vida de projeto segundo o PMBOK:",
    opcoes:["Planejamento, Execução, Controle, Encerramento e Avaliação","Iniciação, Planejamento, Execução, Monitoramento/Controle e Encerramento","Análise, Design, Desenvolvimento, Teste e Implantação","Proposta, Aprovação, Execução, Entrega e Auditoria","Escopo, Tempo, Custo, Qualidade e Risco"],
    correta:1, explicacao:"PMBOK: Iniciação→Planejamento→Execução→Monitoramento e Controle→Encerramento." },
  { id:"a08", area:"adm", sub:"FIFO/PEPS", banca:"CESGRANRIO", ano:2018, dif:"media", tipo:"multipla", enfase:"adm_controle",
    enunciado:"FIFO (First In, First Out) significa:",
    opcoes:["Último que entrou sai primeiro","Aleatório","Primeiro que entrou sai primeiro","Os mais caros saem primeiro","Proporcional ao custo médio"],
    correta:2, explicacao:"FIFO = PEPS: o material mais antigo é consumido primeiro." },
  { id:"a09", area:"adm", sub:"ISO 9001", banca:"CEBRASPE", ano:2024, dif:"media", tipo:"certo_errado", enfase:"adm_controle",
    enunciado:"A ISO 9001 aplica-se a qualquer organização, independentemente de tamanho ou setor.",
    opcoes:["CERTO","ERRADO"], correta:0, explicacao:"CERTO. ISO 9001 é universal para Sistemas de Gestão da Qualidade." },
  { id:"a10", area:"adm", sub:"Estrutura Matricial", banca:"CESGRANRIO", ano:2014, dif:"media", tipo:"multipla", enfase:"adm_controle",
    enunciado:"Estrutura com dupla subordinação (funcional + projeto):",
    opcoes:["Linear","Funcional","Matricial","Divisional","Em rede"],
    correta:2, explicacao:"Estrutura MATRICIAL = dois chefes. Muito usada na Petrobras." },
  // ── LEGISLAÇÃO ──
  { id:"l01", area:"leg", sub:"Natureza Jurídica", banca:"CESGRANRIO", ano:2018, dif:"media", tipo:"multipla", enfase:"adm_controle",
    enunciado:"Natureza jurídica da Petrobras:",
    opcoes:["Autarquia federal","Empresa pública","Sociedade de economia mista","Fundação pública","Órgão da administração direta"],
    correta:2, explicacao:"Sociedade de economia mista: capital misto, majoritariamente estatal, direito privado." },
  { id:"l02", area:"leg", sub:"Lei 9.478/1997 — ANP", banca:"CEBRASPE", ano:2024, dif:"dificil", tipo:"multipla", enfase:"adm_controle",
    enunciado:"Principal atribuição da ANP (Lei 9.478/97):",
    opcoes:["Administrar plataformas","Regular, contratar e fiscalizar as atividades de petróleo, gás e biocombustíveis","Fixar preço de combustíveis","Exploração exclusiva do petróleo","Emitir ações da Petrobras"],
    correta:1, explicacao:"ANP: agência reguladora — REGULA e FISCALIZA o setor." },
  { id:"l03", area:"leg", sub:"Compliance e Ética", banca:"CEBRASPE", ano:2024, dif:"media", tipo:"certo_errado", enfase:"adm_controle",
    enunciado:"É vedado ao empregado receber presentes de fornecedores quando isso puder influenciar decisões comerciais.",
    opcoes:["CERTO","ERRADO"], correta:0, explicacao:"CERTO. Código de ética Petrobras proíbe recebimento que gere conflito de interesses." },
  { id:"l04", area:"leg", sub:"Lei 12.351/2010 — Pré-Sal", banca:"CEBRASPE", ano:2024, dif:"dificil", tipo:"multipla", enfase:"adm_controle",
    enunciado:"No regime de partilha do pré-sal, a Petrobras:",
    opcoes:["Não participa","É operadora obrigatória com participação mínima de 30%","Apenas fiscaliza","Divide lucros igualmente com o Estado","Pode vender participação livremente"],
    correta:1, explicacao:"Lei 12.351/2010: Petrobras = operadora obrigatória, mínimo 30% em todos os blocos." },
  { id:"l05", area:"leg", sub:"Lei Anticorrupção 12.846/2013", banca:"CEBRASPE", ano:2024, dif:"dificil", tipo:"multipla", enfase:"adm_controle",
    enunciado:"Responsabilidade objetiva na Lei 12.846/2013 significa:",
    opcoes:["Só pune com culpa comprovada","Independe de dolo ou culpa — basta o ato prejudicial","Só pessoas físicas podem ser punidas","Aplica-se só a estrangeiras","Depende de condenação criminal prévia"],
    correta:1, explicacao:"Responsabilidade OBJETIVA: empresa responde pelo ato independentemente de dolo/culpa." },
  { id:"l06", area:"leg", sub:"NR-10 — Eletricidade", banca:"CEBRASPE", ano:2024, dif:"media", tipo:"multipla", enfase:"adm_controle",
    enunciado:"A NR-10 trata de:",
    opcoes:["Espaços confinados","Segurança em instalações e serviços em eletricidade","Proteção contra incêndios","EPI","Ergonomia"],
    correta:1, explicacao:"NR-10=Eletricidade; NR-33=Espaços confinados; NR-23=Incêndios; NR-6=EPI; NR-17=Ergonomia." },
  { id:"l07", area:"leg", sub:"CONAMA 398/2008", banca:"CEBRASPE", ano:2024, dif:"media", tipo:"certo_errado", enfase:"adm_controle",
    enunciado:"A Resolução CONAMA 398/2008 obriga instalações com petróleo em águas nacionais a ter um Plano de Emergência Individual (PEI).",
    opcoes:["CERTO","ERRADO"], correta:0, explicacao:"CERTO. PEI obrigatório para plataformas, terminais e dutos com petróleo." },
  { id:"l08", area:"leg", sub:"Valores Petrobras", banca:"CEBRASPE", ano:2024, dif:"facil", tipo:"certo_errado", enfase:"adm_controle",
    enunciado:"A Petrobras tem como valor institucional o compromisso com a segurança das pessoas e do meio ambiente.",
    opcoes:["CERTO","ERRADO"], correta:0, explicacao:"CERTO. Segurança, ética e preservação ambiental são valores centrais da Petrobras." },
  // ── PETRÓLEO ──
  { id:"k01", area:"pet", sub:"Pré-Sal", banca:"CEBRASPE", ano:2024, dif:"media", tipo:"multipla", enfase:"adm_controle",
    enunciado:"O pré-sal fica localizado:",
    opcoes:["Abaixo do Rio Amazonas","No sertão nordestino","Abaixo de camadas de sal no fundo do Oceano Atlântico","Plataforma Continental do Nordeste","Bacia do Amazonas em terra"],
    correta:2, explicacao:"Pré-sal: sob camadas de sal até 2km, profundidades oceânicas de até 7.000m. Campo Tupi descoberto em 2006." },
  { id:"k02", area:"pet", sub:"Destilação Fracionada", banca:"CESGRANRIO", ano:2018, dif:"media", tipo:"multipla", enfase:"adm_controle",
    enunciado:"Processo que separa o petróleo em derivados pelo ponto de ebulição:",
    opcoes:["Craqueamento catalítico","Destilação fracionada","Hidrotratamento","Coqueamento retardado","Reforma catalítica"],
    correta:1, explicacao:"Destilação fracionada = processo primário do refino." },
  { id:"k03", area:"pet", sub:"Blow-Out", banca:"CEBRASPE", ano:2024, dif:"media", tipo:"multipla", enfase:"adm_controle",
    enunciado:"'Blow-out' em plataformas significa:",
    opcoes:["Parada programada","Fluxo descontrolado de petróleo/gás para a superfície","Abandono de poço seco","Sistema de ventilação","Injeção de água"],
    correta:1, explicacao:"Blow-out = erupção descontrolada pela perda de controle da pressão." },
  { id:"k04", area:"pet", sub:"Classificação API", banca:"CESGRANRIO", ano:2014, dif:"dificil", tipo:"multipla", enfase:"adm_controle",
    enunciado:"Petróleo com grau API > 31,1° é classificado como:",
    opcoes:["Extra-pesado","Pesado","Médio","Leve","Ultra-leve"],
    correta:3, explicacao:"API: Leve >31,1°, Médio 22,3°–31,1°, Pesado 10°–22,3°, Extra-pesado <10°." },
  { id:"k05", area:"pet", sub:"QAV — Querosene", banca:"CESGRANRIO", ano:2018, dif:"facil", tipo:"multipla", enfase:"adm_controle",
    enunciado:"Combustível de aviação para aviões a jato:",
    opcoes:["Gasolina","Diesel","Querosene de aviação (QAV)","GLP","Nafta"],
    correta:2, explicacao:"QAV (Jet Fuel) = combustível para jatos. Gasolina=leves, Diesel=pesados, GLP=doméstico, Nafta=petroquímica." },
  { id:"k06", area:"pet", sub:"Bacia de Santos", banca:"CEBRASPE", ano:2024, dif:"media", tipo:"multipla", enfase:"adm_controle",
    enunciado:"Maior parte das reservas do pré-sal está em qual bacia:",
    opcoes:["Bacia de Campos","Bacia de Santos","Bacia do Espírito Santo","Bacia do Recôncavo","Bacia Potiguar"],
    correta:1, explicacao:"Bacia de Santos: campos Lula, Sapinhoá, Atapu. Maior reservatório do pré-sal." },
  { id:"k07", area:"pet", sub:"Metano — Gás Natural", banca:"CESGRANRIO", ano:2018, dif:"media", tipo:"multipla", enfase:"adm_controle",
    enunciado:"Gás natural é composto predominantemente por:",
    opcoes:["Etano","Propano","Metano (CH₄)","Butano","Hexano"],
    correta:2, explicacao:"Metano = 70–90% do gás natural." },
  { id:"k08", area:"pet", sub:"FPSO", banca:"CESGRANRIO", ano:2018, dif:"media", tipo:"multipla", enfase:"adm_controle",
    enunciado:"FPSO significa:",
    opcoes:["Fixed Platform Subsea Operation","Floating Production, Storage and Offloading","Fuel Pipeline and Safety Operations","Federal Petroleum Safety Organization","Floating Petroleum Subsea Offshore"],
    correta:1, explicacao:"FPSO = Unidade Flutuante de Produção, Armazenamento e Transferência." },
  // ── INGLÊS ──
  { id:"e01", area:"ing", sub:"Upstream", banca:"CESGRANRIO", ano:2018, dif:"media", tipo:"multipla", enfase:"adm_controle",
    enunciado:"In the oil industry, 'upstream' refers to:",
    opcoes:["Refining and processing","Distribution and commercialization","Exploration and production of oil and gas","Environmental monitoring","Transportation by pipeline"],
    correta:2, explicacao:"Upstream = E&P (exploração e produção). Midstream = transporte. Downstream = refino." },
  { id:"e02", area:"ing", sub:"PPE", banca:"CESGRANRIO", ano:2018, dif:"media", tipo:"multipla", enfase:"adm_controle",
    enunciado:"'All employees must wear personal protective equipment (PPE).' PPE stands for:",
    opcoes:["Petroleum Production Equipment","Personal Protective Equipment","Platform Performance Evaluation","Pressure Prevention Engineering","Professional Petroleum Expertise"],
    correta:1, explicacao:"PPE = Personal Protective Equipment = EPI." },
  { id:"e03", area:"ing", sub:"Oil Spill", banca:"CESGRANRIO", ano:2014, dif:"facil", tipo:"multipla", enfase:"adm_controle",
    enunciado:"'The oil spill caused severe environmental damage.' 'Oil spill' means:",
    opcoes:["Oil exploration","Oil leak/discharge","Oil production","Oil refining","Oil storage"],
    correta:1, explicacao:"'Oil spill' = derramamento de petróleo." },
  { id:"e04", area:"ing", sub:"Rigorous", banca:"CESGRANRIO", ano:2018, dif:"media", tipo:"multipla", enfase:"adm_controle",
    enunciado:"'Platforms must comply with rigorous safety standards.' 'Rigorous' means:",
    opcoes:["Flexible","Strict and demanding","Optional","Basic","Outdated"],
    correta:1, explicacao:"'Rigorous' = rigoroso, estrito, exigente." },
  // ── CONTABILIDADE ──
  { id:"c01", area:"con", sub:"Ativo Circulante", banca:"CESGRANRIO", ano:2018, dif:"media", tipo:"multipla", enfase:"adm_controle",
    enunciado:"Bens e direitos conversíveis em até 12 meses:",
    opcoes:["Ativo Não Circulante","Passivo Circulante","Ativo Circulante","Patrimônio Líquido","Passivo Não Circulante"],
    correta:2, explicacao:"Ativo Circulante = curto prazo (≤12 meses): caixa, recebíveis, estoques." },
  { id:"c02", area:"con", sub:"Lucro x Prejuízo", banca:"CESGRANRIO", ano:2018, dif:"facil", tipo:"multipla", enfase:"adm_controle",
    enunciado:"Receitas > Despesas = resultado:",
    opcoes:["Prejuízo","Perda","Lucro","Déficit","Passivo"],
    correta:2, explicacao:"Lucro quando receitas superam despesas." },
  { id:"c03", area:"con", sub:"DRE", banca:"CESGRANRIO", ano:2018, dif:"media", tipo:"multipla", enfase:"adm_controle",
    enunciado:"Objetivo principal da DRE:",
    opcoes:["Posição patrimonial em uma data","Fluxo de caixa","Apurar lucro ou prejuízo no período","Movimentações do PL","Ativos imobilizados"],
    correta:2, explicacao:"DRE confronta receitas e despesas do período para apurar resultado." },
  { id:"c04", area:"con", sub:"Depreciação", banca:"CESGRANRIO", ano:2014, dif:"dificil", tipo:"multipla", enfase:"adm_controle",
    enunciado:"Plataforma: R$ 10.000.000, 20 anos, VR=0. Depreciação linear anual:",
    opcoes:["R$ 250.000,00","R$ 400.000,00","R$ 500.000,00","R$ 600.000,00","R$ 1.000.000,00"],
    correta:2, explicacao:"10.000.000/20 = R$ 500.000,00/ano." },
  { id:"c05", area:"con", sub:"Equação Patrimonial", banca:"CESGRANRIO", ano:2018, dif:"facil", tipo:"multipla", enfase:"adm_controle",
    enunciado:"Equação patrimonial fundamental:",
    opcoes:["Ativo = Passivo × PL","Ativo + Passivo = PL","Ativo = Passivo + Patrimônio Líquido","Passivo = Ativo + PL","PL = Ativo × Passivo"],
    correta:2, explicacao:"ATIVO = PASSIVO + PATRIMÔNIO LÍQUIDO. Equação base da contabilidade." },
] as const;

async function main() {
  console.log("🌱 Iniciando seed das questões...");
  try {
    for (const q of QUESTOES) {
      await db.insert(questions).values({
        id: q.id, area: q.area as any, sub: q.sub,
        banca: q.banca as any, ano: q.ano, dif: q.dif as any,
        tipo: q.tipo as any, enunciado: q.enunciado,
        opcoes: q.opcoes as unknown as string[], correta: q.correta,
        explicacao: q.explicacao, enfase: q.enfase,
      }).onConflictDoNothing();
    }
    console.log(`✅ ${QUESTOES.length} questões inseridas com sucesso!`);
  } catch (err) {
    console.error("❌ Erro no seed:", err);
    process.exit(1);
  }
  process.exit(0);
}

main();
